Has been added compatibility with PHP 8 to `magento/semver`
magento/magento-semver pull request #65
Opened 2021-08-23 09:55 UTC by andrewbess

# Description (*)

This pull request (PR) provides compatibility current project with PHP 8.

## Fixed Issues (if relevant)

1. magento/magento2#32872

## Contribution checklist (*)

- [ ] Pull request has a meaningful description of its purpose
- [ ] All commits are accompanied by meaningful commit messages
- [ ] All new or changed code is covered with unit/integration tests (if applicable)
- [ ] All automated tests passed successfully (all builds are green)

2021-08-23 13:45 UTC, ihor-sviziev approved these changes

2021-08-23 17:40 UTC, ihor-sviziev approved these changes

2021-08-30 19:09 UTC, fascinosum requested changes

2021-08-30 21:04 UTC, fascinosum approved these changes

2021-08-31 05:41 UTC, ihor-sviziev commented on composer.json
> +        "laminas/laminas-stdlib": "~3.5.0",
Could you explain why it's needed? All Zend classes were replaced with Laminas.

2021-09-01 09:44 UTC, ihor-sviziev requested changes

2021-09-01 09:44 UTC, ihor-sviziev commented on composer.json
> +        "laminas/laminas-stdlib": "~3.5.0",
@fascinosum Could you explain why it's needed? All Zend classes were replaced with Laminas.

2021-09-02 04:05 UTC, fascinosum commented on composer.json
> +        "laminas/laminas-stdlib": "~3.5.0",
@ihor-sviziev, this plugin will help people who use this library in their CI/CD, to install Laminas packages, even if they have declared dependency on ZF

2021-09-03 03:51 UTC, merged

2021-09-03 05:28 UTC, ihor-sviziev commented
@fascinosum, when we can expect a new version for this svc checker?

2021-09-03 21:14 UTC, fascinosum commented
hi @ihor-sviziev, I think it will be released when full testing cycle for compatibility with Magento with PHP 8.0 is completed